const SearchType={
    ADD_CREDENTIALS:"ADD_CREDENTIALS",
    ADD_AIRLINE:"ADD_AIRLINE",
    REMOVE_AIRLINE:"REMOVE_AIRLINE",
    ADD_FILTERS:"ADD_FILTERS",
    SWITCH_ROUTE:"SWITCH_ROUTE"
}


export default SearchType