export const ReportsTypes = {
  GET_SELL_REPORT: "GET_SELL_REPORT",
  FILTER_SELL_REPORT: "FILTER_SELL_REPORT",
  GET_DETAILS_SELL_REPORT: "GET_DETAILS_SELL_REPORT",
  FILTER_DETAILS_SELL_REPORT: "FILTER_DETAILS_SELL_REPORT",
};
